### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by yahmad3495** [lhvuong11/cse15L-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  -Be sure to count how long it takes and how many key strokes there are with the quickest method you created to make local 
   changes and copying and running WhereAmI.java on a remote server
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job overall! Feel free to leave any questions about the feedback below!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by lhvuong11** [comment]
Even after many tries, I can't seem to ssh-add on Windows. I've tried it on my Mac and my id_rsa is saved just fine (without using the ssh-add of course). 
I'm able to generate a randomart image but am unable to save id_rsa using ssh-agent.

Is a TA or tutor able to help me with this process if I attend their office hours?

**Comment by lhvuong11** [comment]
Here's a screenshot of when I run vsCode as administrator.
![unknown](https://user-images.githubusercontent.com/97763275/150722495-2641df32-82b4-4982-97a4-3a5fec4636b4.png)

**Comment by yahmad3495** [comment]
Hello! Yes I think what you should be looking for is a id_rsa.pub file that is generated after running the keygen command. I believe the .ssh file should be created on the remote server. When you run the keygen command, it should also print out the file path to the public key file that you would need to copy. Attending office hours will definitely help resolve this issue!

**Comment by yahmad3495** [comment]
Just saw the regrade request and updated your score! Feel free to leave any other questions
